# Generated by Django 4.1.13 on 2024-11-15 14:46

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(choices=[(5, '5 minuts'), (10, '10 minuts'), (15, '15 minuts'), (20, '20 minuts')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineSchedule',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('routine_id', models.Field()),
                ('weekday', models.IntegerField(choices=[(0, 'Dilluns'), (1, 'Dimarts'), (2, 'Dimecres'), (3, 'Dijous'), (4, 'Divendres')])),
                ('time_slot', models.IntegerField(choices=[(16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')])),
            ],
            options={
                'db_table': 'gym_trainer_routineschedule',
                'unique_together': {('weekday', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(related_name='routines', to='gym_trainer.exercise')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gym_trainer_routine',
            },
        ),
    ]
